version: '3.5'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      POSTGRES_DB: zabbix
      PG_SHARED_BUFFERS: 1GB
      PG_EFFECTIVE_CACHE_SIZE: 3GB
      PG_WORK_MEM: 16MB
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.2-latest
    depends_on:
      - postgres
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      ZBX_CACHESIZE: 128M
      ZBX_HISTORYCACHESIZE: 128M
      ZBX_HISTORYINDEXCACHESIZE: 32M
      ZBX_TRENDCACHESIZE: 32M
      ZBX_VALUECACHESIZE: 256M
      # Optimasi housekeeper
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_DISABLEHOUSEKEEPER: true  # Nonaktifkan jika pakai PostgreSQL
    ports:
      - "10051:10051"
    restart: unless-stopped
    volumes:
    - ./zbx_env:/etc/zabbix/web:ro
    - ./zabbix/telegram:/usr/lib/zabbix/alertscripts/telegram.sh

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.2-latest
    depends_on:
      - zabbix-server
      - postgres
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Jakarta
    expose:
      - "8080"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - zabbix-web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
